adding Time of Flight sensor drivers
RISE-Dependable-Transport-Systems/WayWise pull request #108
Opened 2024-11-13 10:06 UTC by chrpro

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
I add the drivers for VL53L0Xupdater Time of Flight sensor

* **What is the current behavior?** (You can also link to an open issue here)
There is no ToF sensor on Truck state

* **What is the new behavior (if this is a feature change)?**
The Truckstate will have access to ToF sensor and store the distance from objects on an integer

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

2024-11-20 13:13 UTC, marvind requested changes

2024-11-20 13:13 UTC, marvind commented on sensors/tof/VL53L0Xupdater.h
> +// connects to AS5600 via i2c bus and polls orientation data (angle) periodically
Seems to me this comment was copy-pasted from another file. Needs update

2024-11-20 13:13 UTC, marvind commented on sensors/tof/VL53L0Xupdater.h
> +    int mPollIntervall_ms = 500; // interval (ms) to read from AS5600,
Similar to previous comment as this is not for AS5600

2024-11-20 13:13 UTC, marvind commented on sensors/tof/VL53L0Xupdater.cpp
> +            truckState->setTrailerDistanceToF(iDistance);
Please do not report the distance in mm but use SI base units (meters).

2024-11-20 13:13 UTC, marvind commented on sensors/tof/tofsensorupdater.h
> + * Abstract interface for receiving tof values e.g., magnetic rotary position sensor
"magnetic rotary position sensor" is not correct to my understanding

2024-11-20 13:13 UTC, marvind commented on vehicles/truckstate.h
> +    int trailer_tof_distance; // distance to nearest object
Please follow naming conventions and report distance in SI base units (meters).

2024-11-29 12:46 UTC, r2avula approved these changes
Tested with [waywise_truck.cpp]( https://github.com/RISE-Dependable-Transport-Systems/WayWiseR/blob/6ff50dcc5bad7c9efc8799706c508607a0c4bdfb/waywiser_node/src/waywise_truck.cpp) and works as expected 👍

2024-11-29 20:47 UTC, marvind approved these changes

2024-11-29 20:47 UTC, merged