CameraGimbalUI: check only for gamepads when gimbal is available, ask before capturing it
RISE-Dependable-Transport-Systems/WayWise pull request #57
Opened 2023-11-17 14:23 UTC by marvind

Problem: any gamepad is currently captured by CameraGimbalUI, even when no gimbal is available. This can lead to crashes and undesired behavior (e.g., gamepad should be used in other applications).
Solution: try only to connect to gamepad when gimbal was detected, ask with yes/no dialog whether to connect

2023-11-20 17:11 UTC, rickaha approved these changes
Nice solution

2023-11-20 17:20 UTC, r2avula commented
I am getting a Segmentation fault error due to QMessageBox::question. Perhaps the text is too big for the popup window?

2023-11-20 17:22 UTC, r2avula requested changes

2023-11-20 17:22 UTC, r2avula commented on userinterface/cameragimbalui.cpp
> +                QMessageBox::question(this, "CameraGimbalUI: Gamepad detected", "A gamepad was detected. Should it be used for controlling the vehicle's gimbal?") == QMessageBox::Yes) {
I am getting a Segmentation fault error due to QMessageBox::question. Perhaps the text is too big for the popup window?

2023-11-20 18:11 UTC, r2avula requested changes

2023-11-20 18:11 UTC, r2avula commented on userinterface/cameragimbalui.cpp
> +        } else
```suggestion
            ui->gimbalStatusLabel->setText("Gimbal found. Using gamepad \"" + mGamepad->name() + "\" for controlling it.");
            ui->gimbalStatusLabel->setWordWrap(true);
        } else
```

2023-12-05 20:21 UTC, marvind commented on userinterface/cameragimbalui.cpp
> +            QObject::connect(askUseGamepadMessageBox.get(), &QMessageBox::buttonClicked, [this, yesButton](QAbstractButton *button) {
I now found the issue, and hopefully fixed it... Depending on when the gimbal was detected exactly (either during MavsdkVehicleConnection's construction or later), the messagebox was created from a MAVSDK or Qt thread, respectively. Problems arose when created from MAVSDK thread and I now make sure that it is shown from a Qt thread.

2023-12-06 08:00 UTC, r2avula approved these changes
Seems to work as expected now

2023-12-06 08:00 UTC, merged